#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A program for managing personal PKI infrastructure.

:author: Joe Joyce <joe@decafjoe.com>
:copyright: Copyright (c) Joe Joyce, 2018.
:license: Proprietary
"""
from __future__ import print_function

import argparse
import fnmatch
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

try:
    from configparser import SafeConfigParser
except ImportError:
    from ConfigParser import SafeConfigParser


# =============================================================================
# ----- Globals ---------------------------------------------------------------
# =============================================================================

id_re = re.compile('^[a-zA-Z_-]+$')

args = None
conf = None
fs = None
make = None
parser = None


class D(dict):
    def __getattr__(self, name):
        return self[name]

    def __setattr__(self, name, value):
        self[name] = value

    def __delattr__(self, name):
        del self[name]


class FS(object):
    def __init__(self, dry):
        self.dry = dry
        self._mtimes = {}

    def exists(self, path):
        if self.dry and path in self._mtimes:
            return True
        return os.path.exists(path)

    def mtime(self, path):
        if self.dry and path in self._mtimes:
            return self._mtimes[path]
        return os.stat(path).st_mtime

    def touch(self, path):
        if self.dry:
            self._mtimes[path] = time.time()


# =============================================================================
# ----- Makelike --------------------------------------------------------------
# =============================================================================

GRAPH = []


# ----- Framework -------------------------------------------------------------

def builds(pattern):
    regex = re.compile(pattern)

    def decorate(fn):
        fn._target = regex
        GRAPH.append((regex, fn, [], []))
        return fn

    return decorate


def depends(*patterns, **kwargs):
    which = 2 if kwargs.get('remake_target_on_change', True) else 3

    def decorate(fn):
        for item in GRAPH:
            if item[0] is fn._target:
                item[which].extend(patterns)
                break
        else:
            raise Exception('could not find target pattern!')
        return fn

    return decorate


class Context(D):
    @property
    def sans_target(self):
        rv = Context(**self)
        del rv.target
        return rv

    def p(self, *args):
        target = self.get('target', '<unspecified target>')
        if os.path.isabs(target):
            target = os.path.split(target)[-1]
        print('%s: %s' % (target, ' '.join(args)))

    def resolve(self, section, key):
        rv = getattr(args, key, None)
        if not rv:
            if section:
                rv = conf[section].get(key, None)
            if not rv:
                rv = conf.pki[key]
        return rv

    def resolve_dict(self, section, *keys):
        return dict([(key, self.resolve(section, key)) for key in keys])

    def render(self, src, dst, **extra_context):
        template_context = D(**self)
        template_context.update(extra_context)
        with open(src) as in_f:
            out = in_f.read() % template_context
            with open(dst, 'w') as out_f:
                out_f.write(out)

    def render_csr_conf(
            self,
            section,
            cn,
            email,
            source='%(source)s/csr.conf.in',
            **extra
    ):
        ctx = self.resolve_dict(
            section,
            'country',
            'locality',
            'organization',
            'organizational_unit',
            'state_or_province',
        )
        ctx.update(dict(common_name=cn, email_address=email))
        ctx.update(extra)
        self.render(source % self, self.target, **ctx)

    def run(self, *args):
        self.p(*args)
        if not self.get('dry', True):
            subprocess.check_call(args)

    def openssl(self, *args):
        self.run('openssl', *args)

    def genrsa(self, bits):
        self.openssl('genrsa', '-out', self.target, bits)

    def req(self, name, key_name):
        self.openssl(
            'req',
            '-new',
            '-config', '%s.csr.conf' % name,
            '-key', '%s.key' % key_name,
            '-out', self.target,
        )


class Make(object):
    def __init__(self, **context):
        self._context = context

    def __call__(self, target, **context):
        ctx = Context(**self._context)
        ctx.update(context)
        ctx.target = target

        for regex, fn, deps_remake_templates, deps_noremake_templates in GRAPH:
            match = regex.search(target)
            if match:
                break
        else:
            ctx.p('no build targets matched, assuming this is not built by us')
            return

        target_match_dict = match.groupdict()
        ctx.update(target_match_dict)

        deps = {}
        for template in deps_remake_templates:
            deps[template % ctx] = True
        for template in deps_noremake_templates:
            deps[template % ctx] = False

        needs_make = not fs.exists(target)
        if needs_make:
            ctx.p('does not exist, will need to build it')

        n = len(deps)
        s = 'dependency' if n == 1 else 'dependencies'
        ctx.p('building/checking %i %s' % (n, s))

        target_mtime = 0 if needs_make else fs.mtime(target)
        for dep, remake in deps.items():
            def p(msg):
                filename = dep
                if os.path.isabs(filename):
                    filename = os.path.split(dep)[-1]
                ctx.p('%s:' % filename, msg)

            make(dep, **ctx.sans_target)
            if not needs_make:
                if fs.mtime(dep) > target_mtime:
                    if remake:
                        msg = 'forces target rebuild'
                        needs_make = True
                    else:
                        msg = 'but does not force target rebuild'
                    p('updated more recently than target, %s' % msg)
                else:
                    p('exists but is older than target, no target rebuild')

        if needs_make:
            fn(ctx)
            fs.touch(target)
        else:
            ctx.p('target fully up to date, doing nothing')


# ----- Hacks -----------------------------------------------------------------
#
# Rules that have to be defined first so other rules don't shadow
# them.
#

@depends('cross-a.pem', 'cross-b.pem', 'root-a.pem', 'root-b.pem')
@builds('roots.pem')
def roots_pem(ctx):
    ctx.p('combining root-a, root-b, cross-a, and cross-b pems')
    if not ctx.dry:
        with open(ctx.target, 'w') as out_f:
            for kind in ('root', 'cross'):
                for which in ('a', 'b'):
                    with open('%s-%s.pem' % (kind, which)) as in_f:
                        out_f.write('%s\n' % in_f.read().strip())


# ----- Shared ----------------------------------------------------------------

def depends_ca_db(name):
    extensions = ('crl.srl', 'crt.srl', 'db', 'db.attr')
    filenames = ['%s.%s' % (name, ext) for ext in extensions]
    kwargs = dict(remake_target_on_change=False)
    return depends(*filenames, **kwargs)


@builds('\.db(\.attr)?$')
def empty(ctx):
    ctx.p('making empty file')
    if not ctx.dry:
        with open(ctx.target, 'w') as f:
            f.write('')

@builds('\.srl$')
def initial_serial(ctx):
    ctx.p('populating with initial serial number 01')
    if not ctx.dry:
        with open(ctx.target, 'w') as f:
            f.write('01\n')


@depends('%(name)s.crt')
@builds('(?P<name>.+)\.pem$')
def pem(ctx):
    ctx.openssl(
        'x509',
        '-in', '%s.crt' % ctx.name,
        '-outform', 'pem',
        '-out', ctx.target,
    )


# ----- Root ------------------------------------------------------------------

@depends('%(source)s/root.conf.in')
@builds('root.conf$')
def ca_conf(ctx):
    ctx.p('generating ca config file from root.conf.in')
    if not ctx.dry:
        ctx.render(
            '%(source)s/root.conf.in' % ctx,
            ctx.target,
            **ctx.resolve_dict(None, 'crl_uri')
        )


@builds('root-(?P<which>[ab]).key$')
def root_key(ctx):
    ctx.genrsa(ctx.resolve('root', 'key_length'))


@depends('%(source)s/csr.conf.in')
@builds('(?P<kind>(root|cross))-(?P<which>[ab]).csr.conf$')
def root_csr_conf(ctx):
    ctx.p('generating csr config file from csr.conf.in')
    if not ctx.dry:
        org = ctx.resolve('root', 'organization')
        cn = '%s (%s %s)' % (org, ctx.kind.upper(), ctx.which.upper())
        ctx.render_csr_conf('root', cn, '')


@depends('%(kind)s-%(which)s.csr.conf', 'root-%(which)s.key')
@builds('(?P<kind>(root|cross))-(?P<which>[ab]).csr$')
def root_csr(ctx):
    ctx.req('%s-%s' % (ctx.kind, ctx.which), 'root-%s' % ctx.which)


@depends_ca_db('root-%(which)s')
@depends('root.conf', 'root-%(which)s.csr')
@builds('root-(?P<which>[ab]).crt$')
def root_self_crt(ctx):
    ctx.openssl(
        'ca',
        '-batch',
        '-selfsign',
        '-config', 'root.conf',
        '-name', 'root-%s' % ctx.which,
        '-extensions', 'x509-root',
        '-days', ctx.resolve('root', 'days'),
        '-in', 'root-%s.csr' % ctx.which,
        '-out', ctx.target,
    )


@depends('cross-%(which)s.csr', 'root-a.crt', 'root-b.crt')
@builds('cross-(?P<which>[ab]).crt$')
def root_cross_crt(ctx):
    ctx.openssl(
        'ca',
        '-batch',
        '-config', 'root.conf',
        '-name', 'root-%s' % ('b' if ctx.which == 'a' else 'a'),
        '-extensions', 'x509-cross',
        '-days', ctx.resolve('root', 'days'),
        '-in', 'cross-%s.csr' % ctx.which,
        '-out', ctx.target,
    )


@depends('cross-a.crt', 'cross-b.crt', 'root-a.crt', 'root-b.crt')
@builds('roots.crt$')
def root_combined(ctx):
    ctx.p('combining root-a, root-b, cross-a, and cross-b into master cert')
    if not ctx.dry:
        with open(ctx.target, 'w') as out_f:
            for kind in ('root', 'cross'):
                for which in ('a', 'b'):
                    with open('%s-%s.crt' % (kind, which)) as in_f:
                        out_f.write('%s\n' % in_f.read().strip())


# ----- Intermediate ----------------------------------------------------------

def builds_intermediate(suffix):
    prefix = 'intermediate-'
    pattern = id_re.pattern[1:-1]
    return builds('%s(?P<name>%s)%s' % (prefix, pattern, suffix))


@builds_intermediate('\.key$')
def intermediate_key(ctx):
    ctx.genrsa(ctx.resolve('intermediate', 'key_length'))


@depends('%(source)s/csr.conf.in')
@builds_intermediate('\.csr\.conf$')
def intermediate_csr_conf(ctx):
    ctx.p('generating csr config file from csr.conf.in')
    if not ctx.dry:
        email = ''
        if args.email:
            email = '\nemailAddress = %s' % args.email
        ctx.render_csr_conf('intermediate', args.name[0], email)


@depends('intermediate-%(name)s.csr.conf', 'intermediate-%(name)s.key')
@builds_intermediate('\.csr$')
def intermediate_csr(ctx):
    name = 'intermediate-%s' % ctx.name
    ctx.req(name, name)



@depends('%(source)s/intermediate.conf.in')
@builds_intermediate('\.conf$')
def intermediate_conf(ctx):
    ctx.p('generating intermediate ca config file from intermediate.conf.in')
    if not ctx.dry:
        ctx.render('%(source)s/intermediate.conf.in' % ctx, ctx.target)


@depends_ca_db('intermediate-%(name)s')
@depends('intermediate-%(name)s.conf', 'intermediate-%(name)s.csr')
@builds_intermediate('\.crt$')
def intermediate_crt(ctx):
    ctx.openssl(
        'ca',
        '-batch',
        '-config', 'root.conf',
        '-name', 'cross-%s' % ctx.sign_with,
        '-extensions', 'x509-intermediate',
        '-days', ctx.resolve('intermediate', 'days'),
        '-in', 'intermediate-%s.csr' % ctx.name,
        '-out', ctx.target,
        *ctx.ca_args
    )


# ----- Leaf ------------------------------------------------------------------

def builds_leaf(suffix):
    prefix = 'leaf-'
    pattern = id_re.pattern[1:-1]
    return builds('%s(?P<name>%s)%s' % (prefix, pattern, suffix))


@builds_leaf('.key$')
def leaf_key(ctx):
    ctx.genrsa(ctx.resolve('leaf', 'key_length'))


@depends('%(source)s/csr.conf.in')
@builds_leaf('\.csr\.conf$')
def leaf_csr_conf(ctx):
    ctx.p('generating leaf csr config file from csr.conf.in')
    if not ctx.dry:
        alt_names = '\n'.join(
            ['DNS.%i = %s' % (i, name) for i, name in enumerate(args.name, 1)],
        )
        email = ''
        if args.email:
            email = '\nemailAddress = %s' % args.email
        ctx.render_csr_conf(
            'leaf',
            args.name[0],
            email,
            '%(source)s/leaf.conf.in',
            alt_names=alt_names,
        )


@depends('leaf-%(name)s.csr.conf', 'leaf-%(name)s.key')
@builds_leaf('\.csr$')
def leaf_csr(ctx):
    name = 'leaf-%s' % ctx.name
    ctx.req(name, name)


@depends('leaf-%(name)s.csr')
@builds_leaf('\.crt$')
def leaf_crt(ctx):
    ctx.openssl(
        'ca',
        '-batch',
        '-config', 'intermediate-%s.conf' % ctx.sign_with,
        '-days', ctx.resolve('leaf', 'days'),
        '-in', 'leaf-%s.csr' % ctx.name,
        '-out', ctx.target,
        *ctx.ca_args
    )


# =============================================================================
# ----- Commands --------------------------------------------------------------
# =============================================================================

commands = []


def command(fn):
    commands.append(fn)
    return fn


def add_req_arguments():
    parser.add_argument(
        '--days',
        default=0,
        help='number of days certificate is valid (default: from config)',
        metavar='INT',
        type=int,
    )
    parser.add_argument(
        '--key-length',
        default=0,
        help='key length for generated key (default: from config)',
        metavar='INT',
        type=int,
    )
    parser.add_argument(
        '--country',
        help='country code (default: from config)',
        metavar='STR',
    )
    parser.add_argument(
        '--state-or-province',
        help='state or province code (default: from config)',
        metavar='STR',
    )
    parser.add_argument(
        '--locality',
        help='locality name (default: from config)',
        metavar='STR',
    )
    parser.add_argument(
        '--organization',
        help='organization name (default: from config)',
        metavar='STR',
    )
    parser.add_argument(
        '--organizational-unit',
        help='organizational unit name (default: from config)',
        metavar='STR',
    )


def find_yubikey_certificate():
    cmd = ('yubico-piv-tool', '--slot=9c', '--action=read-cert')
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    stdout, _ = process.communicate()
    if not process.returncode:
        certificate = stdout.strip()
        filenames = os.listdir(args.directory)
        filenames = fnmatch.filter(filenames, 'cross-*.pem') \
                    + fnmatch.filter(filenames, 'intermediate-*.pem')
        for filename in filenames:
            path = os.path.join(args.directory, filename)
            with open(path) as f:
                if f.read().strip() == certificate:
                    return filename
    msg = 'error: no certificate on yubikey, or cert is not in our store'
    print(msg, file=sys.stderr)


@command
def root():
    """Generate the cross-signed PKI roots."""
    parser.add_argument(
        '--crl-uri',
        help='uri for crl distribution point (default: from config)',
        metavar='URI',
    )
    add_req_arguments()

    yield

    make('roots.pem')


@command
def intermediate():
    """Generate the intermediate CA for day-to-day signing."""
    pattern = id_re.pattern

    parser.add_argument(
        'id',
        help='identifier for the certificate (must match %s)' % pattern,
        nargs=1,
    )
    parser.add_argument(
        'name',
        help='name for the certificate (must match %s)' % pattern,
        nargs=1,
    )
    parser.add_argument(
        '--email',
        help='email address (default: <none>)',
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        '-y',
        '--yubikey',
        action='store_true',
        default=False,
        help='use yubikey-based root key for signing the intermediate '
             'certificate',
    )
    group.add_argument(
        '-s',
        '--sign-with',
        choices=('a', 'b'),
        default='a',
        help='sign with an on-disk root cert/key as generated with the root '
             'subcommand (choices: %(choices)s) (default: %(default)s)',
    )

    add_req_arguments()

    yield

    id = args.id[0]

    if not id_re.search(id):
        msg = 'error: identifier "%s" violates regex "%s"' % (id, pattern)
        print(msg, file=sys.stderr)
        yield 1

    if args.yubikey:
        # TODO(jjoyce): implement this
        print('error: cannot currently handle yubikeys', file=sys.stderr)
        yield 1
    else:
        ca_args = ()
        sign_with = args.sign_with
        crt_path = 'cross-%s.crt' % sign_with
        key_path = 'root-%s.key' % sign_with
        for path in (crt_path, key_path):
            if not os.path.exists(path):
                msg = 'error: required file is missing: %s' % path
                print(msg, file=sys.stderr)
                yield 1

    make('intermediate-%s.pem' % id, ca_args=ca_args, sign_with=sign_with)


@command
def leaf():
    """Generate a certificate signed by an intermediate CA."""
    pattern = id_re.pattern

    parser.add_argument(
        'id',
        help='identifier of the generated certificate (must match %s)' \
             % pattern,
        nargs=1,
    )
    parser.add_argument(
        'name',
        help='name(s) to be included in certificate (the first will be the '
             'common name)',
        nargs='+',
    )

    add_req_arguments()

    parser.add_argument(
        '-e',
        '--email',
        default=None,
        help='add specified email address to the csr',
    )

    parser.add_argument(
        '-k',
        '--key-usage',
        default='digitalSignature,keyAgreement,keyEncipherment,nonRepudiation',
        help='comma-separated list of key usages (default: %(default)s)',
    )
    parser.add_argument(
        '-u',
        '--extended-key-usage',
        default='',
        help='comma-separated list of extended key usages (default: <none>)',
    )

    usage_group = parser.add_mutually_exclusive_group()
    usage_group.add_argument(
        '--vpn-client',
        action='store_true',
        default=False,
        help='generate vpn client certificate (overrides -k and -u)',
    )
    usage_group.add_argument(
        '--vpn-server',
        action='store_true',
        default=False,
        help='generate vpn server certificate (overrides -k and -u)',
    )

    sign_group = parser.add_mutually_exclusive_group(required=True)
    sign_group.add_argument(
        '-y',
        '--yubikey',
        action='store_true',
        default=False,
        help='use yubikey-based key for signing the leaf certificate',
    )
    sign_group.add_argument(
        '-s',
        '--sign-with',
        default=None,
        help='sign with an on-disk intermediate cert/key as generated with '
             'the intermediate subcommand (the argument value should be the '
             'id you specified to the intermediate subcommand)',
        metavar='CERT_NAME',
    )

    yield

    id = args.id[0]

    if not id_re.search(id):
        msg = 'error: id "%s" violates regex "%s"' % (id, pattern)
        print(msg, file=sys.stderr)
        yield 1

    if args.yubikey:
        # TODO(jjoyce): implement this
        print('error: cannot currently handle yubikeys', file=sys.stderr)
        yield 1
    else:
        ca_args = ()
        sign_with = args.sign_with
        conf_path = 'intermediate-%s.conf' % args.sign_with
        crt_path = 'intermediate-%s.pem' % args.sign_with
        key_path = 'intermediate-%s.key' % args.sign_with
        for path in (conf_path, crt_path, key_path):
            if not os.path.exists(path):
                msg = 'error: required file is missing: %s' % path
                print(msg, file=sys.stderr)
                yield 1

    if args.vpn_server:
        key_usage = 'digitalSignature,keyAgreement,keyEncipherment,' \
                    'nonRepudiation'
        extended_key_usage = 'serverAuth'
    elif args.vpn_client:
        key_usage = 'digitalSignature,keyEncipherment,nonRepudiation'
        extended_key_usage = 'clientAuth'
    else:
        key_usage = args.key_usage
        extended_key_usage = args.extended_key_usage

    if extended_key_usage:
        fmt = '\nextendedKeyUsage = critical,%s'
        extended_key_usage = fmt % extended_key_usage

    make(
        'leaf-%s.pem' % id,
        ca_args=ca_args,
        extended_key_usage=extended_key_usage,
        key_usage=key_usage,
        sign_with=sign_with,
    )


@command
def ykload():
    """Load a cert/key pair on to a Yubikey."""
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        '-i',
        '--intermediate',
        help='id of the intermediate ca certificate/key to load',
        metavar='ID',
    )
    group.add_argument(
        '-r',
        '--root',
        choices=('a', 'b'),
        help='root ca certificate/key to load (choices: %(choices)s)',
    )

    yield

    print(find_yubikey_certificate())
    yield

    if args.intermediate:
        crt_filename = 'intermediate-%s.crt' % args.intermediate
        key_filename = 'intermediate-%s.key' % args.intermediate
    else:
        crt_filename = 'cross-%s.crt' % args.root
        key_filename = 'root-%s.key' % args.root

    crt_path = os.path.join(args.directory, crt_filename)
    key_path = os.path.join(args.directory, key_filename)

    for path in (crt_path, key_path):
        if not os.path.exists(path):
            msg = 'error: required file is missing: %s' % path
            print(msg, file=sys.stderr)
            yield 1

    subprocess.check_call((
        'yubico-piv-tool',
        '--slot=9c',
        '--action=import-key',
        '--input=%s' % key_path,
        '--pin-policy=always',
        '--touch-policy=always',
    ))
    subprocess.check_call((
        'yubico-piv-tool',
        '--slot=9c',
        '--action=import-certificate',
        '--input=%s' % crt_path,
    ))
    subprocess.check_call(('yubico-piv-tool', '--action=status'))


def main(argv=None, exit=sys.exit):
    global args
    global conf
    global fs
    global make
    global parser

    if argv is None:
        argv = sys.argv

    root_path = os.path.abspath(os.path.dirname(__file__))

    root_parser = argparse.ArgumentParser(
        description='A program for managing personal PKI infrastructure.',
    )
    root_parser.add_argument(
        '-c',
        '--config',
        default=os.path.join(root_path, 'site.conf'),
        help='path to the site configuration file (default: %(default)s)',
        metavar='FILE',
    )
    root_parser.add_argument(
        '-d',
        '--directory',
        default=os.path.join(root_path, 'files'),
        help='directory where everything lives (default: %(default)s)',
        metavar='DIR',
    )
    root_parser.add_argument(
        '--dry',
        action='store_true',
        default=False,
        help='dry run – do not actually run commands, change files, etc',
    )

    subparsers = root_parser.add_subparsers(
        description='Convenience commands for PKI infrastructure.',
    )
    for fn in commands:
        parser = subparsers.add_parser(fn.__name__, help=fn.__doc__)
        generator = fn()
        generator.next()
        parser.set_defaults(_generator=generator)

    args = root_parser.parse_args(argv[1:])

    config_parser = SafeConfigParser()
    with open(os.path.join(root_path, 'defaults.conf')) as f:
        config_parser.readfp(f)
    if os.path.exists(args.config):
        with open(args.config) as f:
            config_parser.readfp(f)

    conf = D()
    key = lambda s: s.replace('-', '_')
    for section in config_parser.sections():
        section_key = key(section)
        conf[section_key] = D()
        for option in config_parser.options(section):
            conf[section_key][key(option)] = config_parser.get(section, option)

    fs = FS(args.dry)
    make = Make(dry=args.dry, source=root_path)

    tmp = None
    wd = args.directory
    if not os.path.exists(args.directory):
        print('%s: mkdir' % args.directory)
        if args.dry:
            wd = tmp = tempfile.mkdtemp()
        else:
            os.mkdir(args.directory)

    os.chdir(wd)
    try:
        rv = args._generator.next()
    except StopIteration:
        rv = 0
    finally:
        if tmp is not None:
            os.chdir(os.path.sep)
            shutil.rmtree(tmp)

    exit(rv)


if __name__ == '__main__':
    main()

